version: "3"
services:
  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db_justify
    restart: unless-stopped
    tty: true
    ports:
      - "4040:3306"
    environment:
      MYSQL_DATABASE: ''
      MYSQL_ROOT_PASSWORD: ''
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
    networks:
      - app-network
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]

  #Node Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: app_justify
    restart: unless-stopped
    tty: true
    env_file: .env
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver_justify
    restart: unless-stopped
    tty: true
    ports:
      - "4000:80"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
  node_modules:
